language = {
vi: "Tiếng Việt",
en: "English",
ma: "Mã",
bo_qua: "Bỏ qua",
stt: "STT",
so_diem: "Số điểm",
che_do_hien_thi: "Chế độ hiển thị",
ket_thuc: "Kết thúc",
thoi_gian_ghi_nho: "Thời gian ghi nhớ",
mot_phut_de_bat_dau: "Bạn có một phút để chuẩn bị",
san_sang: "Sẵn sàng",
bat_dau: "Bắt đầu",
phut: "Phút",
cot: "Cột",
xep_hang: "Xếp hạng",
luat_choi: "Luật chơi",
huan_luyen: "Học tập",
dang_nhap: "Đăng nhập",
choi_game: "Thi đấu",
super_me: "Super me",
chon_cap_do: "Chọn cấp độ",
chon_man: "Chọn màn chơi",
luyen_tap_tu_do: "Luyện tập tự do",
thi_quoc_gia: "Thi quốc gia",
thi_quoc_te: "Thi quốc tế",
thi_the_gioi: "Thi thế giới",
ten_va_khuon_mat: "Tên và khuôn mặt",
so_nhi_phan: "Số nhị phân",
so_ngau_nhien: "Số ngẫu nhiên",
hinh_anh_truu_tuong: "Hình ảnh trừu tượng",
nho_so_nhanh: "Nhớ số nhanh",
nam_lich_su: "Năm lịch sử, tương lai",
tu_ngau_nhien: "Từ ngẫu nhiên",
nghe_nho_so: "Nghe nhớ số",
ok: "Chơi",
lich_su_choi: "Lịch sử chơi",
ngon_ngu: "Ngôn ngữ",
bai_ngau_nhien: "Bài ngẫu nhiên",
nho_bai_nhanh: "Nhớ bài nhanh",
dang_doc_so: "Đang đọc số",
chao_mung: "Chào mừng bạn",
gioi_thieu_dang_nhap: "Rất vui khi gặp bạn!<br/>Sẵn sàng luyện tập cho trí não ghi nhớ tốt hơn nào.",
diem_so: "Điểm số",
thoi_gian: "Thời gian",
ngay: "Ngày",
cau_hinh: "Cấu hình",
ho_ten: "Họ và tên",
do_tuoi: "Độ tuổi",
noi_song: "Nơi sống",
chi_tiet: "Chi tiết",
tat_ca: "Tất cả",
tuoi: "Tuổi",
hom_nay: "Hôm nay",
hom_qua: "Hôm qua",
tuan_nay: "Tuần này",
ngay_truoc: "Ngày trước",
xep_hang_cua_hang: "Thứ hạng của bạn",
dang_xuat: "Đăng xuất",
thoi_gian_nho: "Thời gian nhớ",
thoi_gian_tra_loi: "Thời gian trả lời",
khong_co_du_lieu: "Không có dữ liệu",
dang_tai: "Đang tải...",
nam_nay: "Năm nay",
thong_tin_ca_nhan: "Thông tin cá nhân",
cap_nhat_thong_tin: "Cập nhật thông tin",
gioi_tinh: "Giới tính",
email: "Email",
gioi_tinh_nam: "Nam",
gioi_tinh_nu: "Nữ",
tai_khoan: "Tài khoản",
so_dien_thoai: "Số điện thoại",
submit: "Cập nhật",
dang_nhap_voi: "Đăng nhập với",
man_choi: "Màn chơi",
cap_do: "Cấp độ",
thoi_gian_tao: "Thời gian tạo",
thong_bao_bo_qua_sang_tra_loi: "Bạn đã sẵn sàng chuyển sang phần Trả lời?",
thong_bao_bo_qua_de_ket_thuc: "Bạn muốn kết thúc bài thi này?",
tieu_de_ung_dung: "SuperMe: Siêu trí nhớ",
dfsdf: 1}
