language = {
vi: "Tiếng Việt",
en: "English",
ma: "Code",
bo_qua: "Skip",
stt: "No",
so_diem: "Score",
che_do_hien_thi: "Display mode",
ket_thuc: "Finish",
thoi_gian_ghi_nho: "Total memorisation time",
mot_phut_de_bat_dau: "One-minute mental presentation time",
san_sang: "Neurons on the ready",
bat_dau: "GO",
phut: "Minutes",
cot: "Column",
xep_hang: "Ranking",
luat_choi: "Competition rules",
huan_luyen: "Training",
dang_nhap: "Login",
choi_game: "Compete",
super_me: "Super me",
chon_cap_do: "Choose Mode",
chon_man: "Choose Competition",
luyen_tap_tu_do: "Training",
thi_quoc_gia: "National",
thi_quoc_te: "International",
thi_the_gioi: "World champion",
ten_va_khuon_mat: "Name and Face",
so_nhi_phan: "Random binary",
so_ngau_nhien: "Random numbers",
hinh_anh_truu_tuong: "Abstract images",
nho_so_nhanh: "Speed numbers",
nam_lich_su: "Hictoric/Furture dates",
tu_ngau_nhien: "Random words",
nghe_nho_so: "Spoken numbers",
ok: "Start",
lich_su_choi: "Training record",
ngon_ngu: "Language",
bai_ngau_nhien: "Random card",
nho_bai_nhanh: "Speed card",
dang_doc_so: "Speaking number",
chao_mung: "Welcome",
diem_so: "Score",
thoi_gian: "Time",
ngay: "Date",
cau_hinh: "Setting",
ho_ten: "Full name",
do_tuoi: "Age",
noi_song: "Location",
chi_tiet: "Detail",
tat_ca: "All",
tuoi: "Ages",
hom_nay: "Today",
hom_qua: "Yesterday",
tuan_nay: "This week",
ngay_truoc: "Days ago",
xep_hang_cua_hang: "Your rank",
dang_xuat: "Signout",
thoi_gian_nho: "Remember time",
thoi_gian_tra_loi: "Recall time",
khong_co_du_lieu: "No data",
dang_tai: "Loading...",
nam_nay: "This year",
thong_tin_ca_nhan: "Profile",
cap_nhat_thong_tin: "Update profile",
gioi_tinh: "Gender",
email: "Email",
gioi_tinh_nam: "Male",
gioi_tinh_nu: "Female",
tai_khoan: "Profile",
so_dien_thoai: "Phone number",
submit: "Update",
dang_nhap_voi: "Login with",
man_choi: "Competition",
cap_do: "Game mode",
thoi_gian_tao: "Created time",
thong_bao_bo_qua_sang_tra_loi: "Are you ready to answer the questions?",
thong_bao_bo_qua_de_ket_thuc: "Are you sure you want to finish this exam?",
tieu_de_ung_dung: "SuperMe: Super memory",
bo_bai: "Deck of cards",
chen_phai: "Insert right",
chen_trai: "Insert left",
xoa: "Remove",
cai_dat_ung_dung: "Download it from Google Play and Apple Store",
can_kich_hoat: "This function is only for Combo students of matmatainang.vn. Please register now to receive the application",
dang_ky: "Register",
ban_dang_o_level: "Your current level is",
ban_vua_dat_duoc_cap_do: "CONGRATULATIONS<br/><br/>You have just level up to",
de_dat_duoc_cap_do_tiep_theo: "To level up, you must complete below:",
trang_thai: "Status",
chua_hoan_thanh: "Not passed",
hoan_thanh: "Passed",
dfsdf: 1}
